apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
stringData:
  S3_ACCESS_KEY: 131408522096174073@ecstestdrive.emc.com
  S3_SECRET_KEY: o+aJUhILE90kDIRkOeK6/4S1mgbCMTiXo3mSZJdb
  S3_ENDPOINT: http://131408522096174073.public.ecstestdrive.com
  S3_BUCKET: data
