apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  labels:
    app: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui-lb
  labels:
    app: spark
    role: master
spec:
  type: LoadBalancer
  selector:
    app: spark
    role: master
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    app: spark
    role: thrift
spec:
  type: LoadBalancer
  selector:
    app: spark
    role: thrift
  ports:
    - name: thrift
      port: 10000
      targetPort: 10000
